version: "3"

services:

  # backend API on port 3000
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
    working_dir: /app
    command: npm start

  # frontend on port 8080
  frontend:
    build: .
    environment:
      API_URL: http://api:3000
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    working_dir: /app
    links:
      - api
    command: npm start